# Site settings
title: My Portfolio
email: your-email@example.com
description: >-
  My personal portfolio and blog where I share my projects and thoughts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mnethmina.github.io" # the base hostname & protocol for your site
github_username: MHMNP2021

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/
